# This compose file is used for end-to-end testing the UI against the Aerie services.
# It assumes the main Aerie repository has been cloned into this repo as a sub-directory called 'aerie'.
# See .github/workflows/test.yml for how this file is utilized.

version: '3.7'
services:
  aerie_gateway:
    container_name: aerie_gateway
    depends_on: ['postgres']
    environment:
      AUTH_TYPE: none
      GQL_API_URL: http://localhost:8080/v1/graphql
      HASURA_GRAPHQL_JWT_SECRET: '${HASURA_GRAPHQL_JWT_SECRET}'
      LOG_FILE: console
      LOG_LEVEL: debug
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
      PORT: 9000
      AERIE_DB_HOST: postgres
      AERIE_DB_PORT: 5432
      GATEWAY_DB_USER: '${GATEWAY_USERNAME}'
      GATEWAY_DB_PASSWORD: '${GATEWAY_PASSWORD}'
    image: 'ghcr.io/nasa-ammos/aerie-gateway:dev-2.11.2'
    ports: ['9000:9000']
    restart: always
    volumes:
      - aerie_file_store:/app/files
  aerie_merlin:
    container_name: aerie_merlin
    depends_on: ['postgres']
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_GRAPHQL_URL: http://hasura:8080/v1/graphql
      AERIE_DB_HOST: postgres
      AERIE_DB_PORT: 5432
      MERLIN_DB_USER: '${MERLIN_USERNAME}'
      MERLIN_DB_PASSWORD: '${MERLIN_PASSWORD}'
      MERLIN_LOCAL_STORE: /usr/src/app/merlin_file_store
      MERLIN_PORT: 27183
      MERLIN_USE_NEW_CONSTRAINT_PIPELINE: 'true'
      JAVA_OPTS: >
        -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
        -Dorg.slf4j.simpleLogger.log.com.zaxxer.hikari=INFO
        -Dorg.slf4j.simpleLogger.logFile=System.err
      UNTRUE_PLAN_START: '2000-01-01T11:58:55.816Z'
    image: 'ghcr.io/nasa-ammos/aerie-merlin:dev-2.11.2'
    ports: ['27183:27183']
    restart: always
    volumes:
      - aerie_file_store:/usr/src/app/merlin_file_store
  aerie_merlin_worker:
    container_name: aerie_merlin_worker
    depends_on: ['postgres']
    environment:
      AERIE_DB_HOST: postgres
      AERIE_DB_PORT: 5432
      MERLIN_DB_USER: '${MERLIN_USERNAME}'
      MERLIN_DB_PASSWORD: '${MERLIN_PASSWORD}'
      MERLIN_WORKER_LOCAL_STORE: /usr/src/app/merlin_file_store
      SIMULATION_PROGRESS_POLL_PERIOD_MILLIS: 2000
      JAVA_OPTS: >
        -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
        -Dorg.slf4j.simpleLogger.log.com.zaxxer.hikari=INFO
        -Dorg.slf4j.simpleLogger.logFile=System.err
      UNTRUE_PLAN_START: '2000-01-01T11:58:55.816Z'
    image: 'ghcr.io/nasa-ammos/aerie-merlin-worker:dev-2.11.2'
    ports: ['27187:8080']
    restart: always
    volumes:
      - aerie_file_store:/usr/src/app/merlin_file_store:ro
  aerie_scheduler:
    container_name: aerie_scheduler
    depends_on: ['aerie_merlin', 'postgres']
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
      MERLIN_GRAPHQL_URL: http://hasura:8080/v1/graphql
      AERIE_DB_HOST: postgres
      AERIE_DB_PORT: 5432
      SCHEDULER_DB_USER: '${SCHEDULER_USERNAME}'
      SCHEDULER_DB_PASSWORD: '${SCHEDULER_PASSWORD}'
      SCHEDULER_PORT: 27185
      JAVA_OPTS: >
        -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
        -Dorg.slf4j.simpleLogger.log.com.zaxxer.hikari=INFO
        -Dorg.slf4j.simpleLogger.logFile=System.err
    image: 'ghcr.io/nasa-ammos/aerie-scheduler:dev-2.11.2'
    ports: ['27185:27185']
    restart: always
    volumes:
      - aerie_file_store:/usr/src/app/merlin_file_store
  aerie_scheduler_worker:
    container_name: aerie_scheduler_worker
    depends_on: ['postgres']
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
      MERLIN_GRAPHQL_URL: http://hasura:8080/v1/graphql
      MERLIN_LOCAL_STORE: /usr/src/app/merlin_file_store
      SCHEDULER_OUTPUT_MODE: UpdateInputPlanWithNewActivities
      SCHEDULER_RULES_JAR: /usr/src/app/merlin_file_store/scheduler_rules.jar
      AERIE_DB_HOST: postgres
      AERIE_DB_PORT: 5432
      SCHEDULER_DB_USER: '${SCHEDULER_USERNAME}'
      SCHEDULER_DB_PASSWORD: '${SCHEDULER_PASSWORD}'
      JAVA_OPTS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
        -Dorg.slf4j.simpleLogger.log.com.zaxxer.hikari=INFO
        -Dorg.slf4j.simpleLogger.logFile=System.err
    image: 'ghcr.io/nasa-ammos/aerie-scheduler-worker:dev-2.11.2'
    ports: ['27189:8080']
    restart: always
    volumes:
      - aerie_file_store:/usr/src/app/merlin_file_store:ro
  aerie_sequencing:
    container_name: aerie_sequencing
    depends_on: ['postgres']
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
      LOG_FILE: console
      LOG_LEVEL: debug
      MERLIN_GRAPHQL_URL: http://hasura:8080/v1/graphql
      AERIE_DB_HOST: postgres
      AERIE_DB_PORT: 5432
      SEQUENCING_DB_USER: '${SEQUENCING_USERNAME}'
      SEQUENCING_DB_PASSWORD: '${SEQUENCING_PASSWORD}'
      SEQUENCING_LOCAL_STORE: /usr/src/app/sequencing_file_store
      SEQUENCING_SERVER_PORT: 27184
    image: 'ghcr.io/nasa-ammos/aerie-sequencing:dev-2.11.2'
    ports: ['27184:27184']
    restart: always
    volumes:
      - aerie_file_store:/usr/src/app/sequencing_file_store
  hasura:
    container_name: aerie_hasura
    depends_on: ['postgres']
    environment:
      AERIE_DATABASE_URL: 'postgres://${AERIE_USERNAME}:${AERIE_PASSWORD}@postgres:5432/aerie?options=-c%20search_path%3Dutil_functions%2Chasura%2Cpermissions%2Ctags%2Cmerlin%2Cscheduler%2Csequencing%2Cpublic'
      AERIE_MERLIN_URL: 'http://aerie_merlin:27183'
      AERIE_SCHEDULER_URL: 'http://aerie_scheduler:27185'
      AERIE_SEQUENCING_URL: 'http://aerie_sequencing:27184'
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS: false
      HASURA_GRAPHQL_JWT_SECRET: '${HASURA_GRAPHQL_JWT_SECRET}'
      HASURA_GRAPHQL_LOG_LEVEL: info
      HASURA_GRAPHQL_METADATA_DATABASE_URL: 'postgres://${AERIE_USERNAME}:${AERIE_PASSWORD}@postgres:5432/aerie_hasura'
      HASURA_GRAPHQL_METADATA_DIR: /hasura-metadata
    image: 'ghcr.io/nasa-ammos/aerie-hasura:dev-2.11.2'
    ports: ['8080:8080']
    restart: always
  postgres:
    container_name: aerie_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      AERIE_USERNAME: '${AERIE_USERNAME}'
      AERIE_PASSWORD: '${AERIE_PASSWORD}'
      GATEWAY_DB_USER: '${GATEWAY_USERNAME}'
      GATEWAY_DB_PASSWORD: '${GATEWAY_PASSWORD}'
      MERLIN_DB_USER: '${MERLIN_USERNAME}'
      MERLIN_DB_PASSWORD: '${MERLIN_PASSWORD}'
      SCHEDULER_DB_USER: '${SCHEDULER_USERNAME}'
      SCHEDULER_DB_PASSWORD: '${SCHEDULER_PASSWORD}'
      SEQUENCING_DB_USER: '${SEQUENCING_USERNAME}'
      SEQUENCING_DB_PASSWORD: '${SEQUENCING_PASSWORD}'
    image: 'ghcr.io/nasa-ammos/aerie-postgres:develop'
    ports: ['5432:5432']
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  aerie_file_store:
  postgres_data:
