name: 'Feature Request'
description: Request a new Aerie UI feature
labels: ['feature']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request this feature! If your feature request is complex or substantial enough to warrant in-depth discussion, maintainers may close the issue and ask you to open a [Discussion](https://github.com/NASA-AMMOS/aerie-ui/discussions).
  - type: dropdown
    id: checked-for-duplicates
    attributes:
      label: Checked for duplicates
      description: Have you checked for duplicate issue tickets?
      options:
        - "Yes - I've already checked"
        - "No - I haven't checked"
    validations:
      required: true
  - type: dropdown
    id: checked-alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered alternative solutions to your feature request?
      options:
        - "Yes - and alternatives don't suffice"
        - "No - I haven't considered"
    validations:
      required: true
  - type: textarea
    id: related-problems
    attributes:
      label: Related problems
      description: Is your feature request related to any problems? Please help us understand if so, including linking to any other issue tickets.
      placeholder: Tell us the problems
      value: "I'm frustrated when [...] happens as documented in issue-XYZ"
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the feature request
      description: A clear and concise description of your request.
      placeholder: Tell us what you want
      value: 'I need or want [...]'
    validations:
      required: true
