const { execSync } = require('child_process');
const { writeFileSync } = require('fs');

function getBranch() {
  if (process.env.GIT_BRANCH) {
    return process.env.GIT_BRANCH;
  } else {
    const branch = execSync('git rev-parse --abbrev-ref HEAD');
    return branch.toString().trim();
  }
}

function getCommit() {
  const commit = execSync('git rev-parse --short HEAD');
  return commit.toString().trim();
}

function main() {
  const branch = getBranch();
  const commit = getCommit();
  const date = new Date().toLocaleString();
  const packageName = process.env.npm_package_name;
  const packageVersion = process.env.npm_package_version;

  const content = [
    `// This file is automatically generated by the 'git-version.js' script.`,
    `// Run 'npm run version' to regenerate it if needed.`,
    `// ${date}\n`,
    `export interface Version {`,
    `  branch: string;`,
    `  commit: string;`,
    `  date: string;`,
    `  name: string;`,
    `}\n`,
    `export const version: Version = {`,
    `  branch: '${branch}',`,
    `  commit: '${commit}',`,
    `  date: '${date}',`,
    `  name: '${packageName}-${packageVersion}',`,
    `};\n`,
  ].join('\n');

  writeFileSync('src/environments/version.ts', content, { encoding: 'utf8' });
}

main();
