name: Lint

on:
  pull_request:
    branches:
      - develop
      - dev-[0-9]+.[0-9]+.[0-9]+
  push:
    branches:
      - develop
    tags:
      - v*
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Svelte Sync
        run: npm run sync
      - name: Count Lines of Code
        run: npm run cloc
      - name: Prettier
        run: npm run format:check
      - name: ESLint
        run: npm run lint
      - name: Stylelint
        run: npm run lint:css
      - name: Svelte Check
        run: npm run check
